### ISSUE TITLE
Font Sharpening

### ISSUE THREAD

**Issue by dagilleland** [dgilleland/dgilleland.github.io#56]
Add the following style to your site:

```css
:root {
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  font-smooth: never;
}
```

From [7 Tips for Making Any Website Look Beautiful](https://youtu.be/C-UeBdtopdA?si=5G1TdrjtUrrm13el)
